/* maps.js — карты из оригинальной PyGame-версии "Baldy and cops".
   T — стена, C — игрок, P — мент, A — выход. */
(function(g){
  g.MAPS = {
    "1": [
      "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
      "TP..T...T....TT........T...T",
      "T.T...T.T.TT.TT.TTT.TTTT.T.T",
      "TTTTTTT.T..T.TT...T.T....T.T",
      "T.......TT.T.TTTT.T.T.TTTT.T",
      "T.TTTTTTT..T.TT...T.T....T.T",
      "T.T.....T.TT.TT.TTT.TTTT.T.T",
      "T.T.....T..T.TT...T....T.T.T",
      "T..........TCTTTT.TT.T...T.T",
      "TTTTTT.TTTTTTTTTT...TTTTTT.T",
      "T....T.T.....TTTTTT.TTTTTT.T",
      "T.TT...T.....TT..........T.T",
      "T.TTTTTTTTTTTTT.T........T.T",
      "T............TT...TTTTT..T.T",
      "TTTTTTTTTTTT.TTTT.T...T..T.T",
      "T............TA...T.T.T..T.T",
      "T.TTTTTTTTTTTTTTTTT.T.TTTT.T",
      "T...................T......T",
      "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    ],
    "2": [
      "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
      "TC.....T...TATTT...T...T...T",
      "TTTTTT.T.T.T.....T.T.T.T.T.T",
      "T....T.T.T.TTTTTTT.T.T.T.T.T",
      "T.TT...T.T...TT....T.T.T.T.T",
      "T..TTTTT.TTT.TT.TTTT.T.T.T.T",
      "TT.T...T.T...TT....T.T.T.T.T",
      "T..T.T.T.T.TTTTTTT.T.T.T.T.T",
      "T....T...T...TT....T.T.T.T.T",
      "TTTTTTTTTTTT.TT.TTTT.T.T.T.T",
      "TTTTTTTTTTTT.TT.TTTT.T.T.T.T",
      "TT...T....T..TT....T.T.T.T.T",
      "T..T.T.T..T..TTTTT.T.T.T.T.T",
      "T.T..T..T.T.....T..T.T.T.T.T",
      "T..T..T.T.T..TT.T.TT.T.T.T.T",
      "TT.TT.T.T.TT.TT.T....T...T.T",
      "T..T..T.T.T..TT.TTTTTTTTTT.T",
      "TPT.....T...TTT............T",
      "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    ],
    "3": [
      "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
      "TC.............T...T.................T.T",
      "TTTTTTTTT.T..T...T...........TT.T..T...T",
      "TTTTTTTTT.....T.....T....T....T...T.TT.T",
      "TTTTTTT...TT...T.T..T...........T......T",
      "T.....T......T.T....T.T......T.........T",
      "TTTTT.T.....T....TT.TT.T.T.T..T..T.....T",
      "T.....TTTTT.TT..TTT.TT....T.........T..T",
      "T.....T....T..TT......T.......T.T..T..TT",
      "T.TT.TT.T..T...T..TT..T...T.T.......T..T",
      "TT...T....TT..T...T..T..T........T.....T",
      "T..TT.TTTT...........T...T..TT.T.......T",
      "TT.........T....T..............T....T..T",
      "T.T..TTTTTT.T.T...TT.T....T.T.T.TTT..TTT",
      "TT.T.T.T.....T...T.......T..TTT.T..T.T.T",
      "TT.TTT.....T........T..T......T...T....T",
      "T....TT.T..T.TTT.TTTT....T.T...T.T...T.T",
      "T..TT.......T......T..T..T..T...TT.T...T",
      "T...T...TT.T...T...........T..T.TT..TT.T",
      "TT..T.TT..T...T.T.T.T.T.TT..T..T..TT...T",
      "T......................................T",
      "TTTTTTTTTTTTTTTTTTT.TTTTTTTTTTTTTTTTTTTT",
      "T.................T.T..................T",
      "T.TTTTTTTTTTTTTTT.T.T.TTTTTTTTTTTTTTTT.T",
      "T.T.............T...T.T..............T.T",
      "T.T.TTTTTTTTTTT.TTTTT.T.TTTTTTTTTTTT.T.T",
      "T.T.TTTTTTTTTTT.......T.T..........T...T",
      "T.T.T........TTTTTTTTTT.T.TTTTTTTT.TTTTT",
      "T...T.TTTTTT.TT.......T.T.T.....TT.....T",
      "TTTTT.T....T....TTTTT.T...T.TTT.TTTTTT.T",
      "T...T.T....T.TTTT...T.TTTTT.T.T.T....T.T",
      "T...T.T....T........T.......T.T.T.TTTT.T",
      "T.....T....TTTT.TTTTTTTTTTTTT.T.T.T....T",
      "T.TTTTT......T..T.........TAT.T.T.T.TTTT",
      "T.T..........T..T.........T.T.T.T.T....T",
      "T.T..........T..TTTTTTTT..T.TTT.T.TTTT.T",
      "T.T..........T.........T..T...T.T....T.T",
      "T.TTTTTTTTTTTTTTTTTTTTTTT.TTT.T.TTTTTT.T",
      "T.............................T........T",
      "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    ],
  };
  // Разворачиваем строки в массив ячеек
  for (var k in g.MAPS) {
    g.MAPS[k] = g.MAPS[k].map(function (row) {
      return row.split('').map(function (ch) { return ch === '.' ? '' : ch + '00'; });
    });
  }
})(window);
